### ISSUE TITLE
[META] Add more information than just module update status

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/backdrop_upgrade_status#17]
I have a spreadsheet that I prepare when I'm working on Drupal to Backdrop upgrades, and it includes a tab for contrib modules, but also has a bunch of other information. I'd love to automate the collection and display of this information from existing Drupal 7 sites, and it seems that there's no better place for it than within this module. I haven't yet decided where it should go (perhaps on sub-tabs? Perhaps a separate report page?) but here's a list of what I'd like to include:

- [x]  Modules (Drupal core)
- [x]  Modules (Drupal contrib)
- [x]  Modules (custom)
- [x]  Content overview (node types, and counts of each type)
- [x]  Taxonomy overview (term types, and counts of each type)
- [x]  User overview (account statuses, and counts of each type)
- [x]  Paragraph overview (paragraph types, and counts of each type)
- [x]  Field overview (and field types that might be complicated to upgrade into B)
- [x]  Views overview (and views that are in code instead of in the DB)
- [x] Features overview (and content types that need to be updated)

I'm not yet sure how to tackle these, since it will involve some "evaluation" of the custom code, but maybe for now we can simply list that these exist, and expand information about them at a later point in time?
* Custom module(s) and approx complexity of each
* Custom theme(s) and approx complexity of each

And here are some nice-to-haves
* Panels => Layouts conversions (if Panels was used in D7) and possible mappings
* Contexts (if Contexts was used in D7)

**Comment by jenlampton** [comment]
I've started [a PR with a reports page](https://github.com/backdrop-contrib/backdrop_upgrade_status/pull/19) and so far it has content types, vocabularies, and users. 

<img width="1525" alt="Screen Shot 2021-04-29 at 5 56 50 PM" src="https://user-images.githubusercontent.com/397895/116635712-4fe85b80-a914-11eb-9d8a-8477e48a5f72.png">
<img width="1534" alt="Screen Shot 2021-04-29 at 5 56 57 PM" src="https://user-images.githubusercontent.com/397895/116635716-51b21f00-a914-11eb-815f-cc7d5afbf337.png">

**Comment by jenlampton** [comment]
Pushed some commits that added field data:
<img width="1528" alt="Screen Shot 2021-04-29 at 6 39 34 PM" src="https://user-images.githubusercontent.com/397895/116638048-48c44c00-a91a-11eb-9649-017d42ffec25.png">

**Comment by jenlampton** [comment]
I've pushed some commits that added Field data:

<img width="1559" alt="Screen Shot 2021-04-29 at 6 54 56 PM" src="https://user-images.githubusercontent.com/397895/116639130-a22d7a80-a91c-11eb-8d07-545e07e5e5a7.png">


I've pushed some commits that added paragraph info:

<img width="1551" alt="Screen Shot 2021-04-29 at 6 55 49 PM" src="https://user-images.githubusercontent.com/397895/116639083-87f39c80-a91c-11eb-9834-231fd702ea93.png">

**Comment by jenlampton** [comment]
I've pushed an update that adds views data, and ads color coding. Things that need to be changed before an upgrade are red (error) and things that could use a review are yellow (warning).

<img width="1552" alt="Screen Shot 2021-04-29 at 8 31 23 PM" src="https://user-images.githubusercontent.com/397895/116645090-e6734780-a929-11eb-81dd-731b77e1e819.png">

**Comment by jenlampton** [comment]
I've added a "todo" list to the top of this form, but now I'm wondering if having it right there is best, or if it should be provided by a separate submodule?

<img width="1555" alt="Screen Shot 2021-04-29 at 8 44 17 PM" src="https://user-images.githubusercontent.com/397895/116646289-87fb9880-a92c-11eb-9846-87e3bd1641c6.png">


Originally I was thinking having it here could be helpful, as it would inform people in the "evaluation" phase what to do during the upgrade. But now I'm wondering about that...  could use some input!

**Comment by jenlampton** [comment]
I've now also added three sections for modules: core, contrib, and custom. Each shows enabled projects, and suggestions about how to handle each one:

Core:
<img width="1369" alt="Screen Shot 2021-05-05 at 5 25 11 PM" src="https://user-images.githubusercontent.com/397895/117225308-e01c1a00-adc6-11eb-9e0b-63f97723dd01.png">

Contrib: 
<img width="1394" alt="Screen Shot 2021-05-05 at 6 35 48 PM" src="https://user-images.githubusercontent.com/397895/117229887-c41d7600-add0-11eb-8efc-622f0fff6a50.png">

**Comment by jenlampton** [comment]
I've added a section for features: 
<img width="1346" alt="Screen Shot 2021-05-06 at 9 59 31 PM" src="https://user-images.githubusercontent.com/397895/117399959-87c44580-aeb6-11eb-8125-b166e5a9d76b.png">

**Comment by albanycomputers** [comment]
Sounds like a good plan.  Go for it.

**Comment by maxmeno** [comment]
The report it's a GREAT idea, Jen! Please do it!

**Comment by diannevolek** [comment]
Do it!!!

**Comment by herbdool** [comment]
Thumbs up @jenlampton . Didn't see this until now

**Comment by Wylbur** [comment]
This looks really great Jen, let's do it!

**Comment by jenlampton** [comment]
Thanks everyone! I've merged the PR :)
